# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/hello-world',
                'doc_host': 'https://nitinverma78.github.io',
                'git_url': 'https://github.com/nitinverma78/hello-world',
                'lib_path': 'hello_world'},
  'syms': { 'hello_world.bench': { 'hello_world.bench._get_scope': ('bench.html#_get_scope', 'hello_world/bench.py'),
                                   'hello_world.bench._run': ('bench.html#_run', 'hello_world/bench.py'),
                                   'hello_world.bench._run_alg': ('bench.html#_run_alg', 'hello_world/bench.py'),
                                   'hello_world.bench._timeit': ('bench.html#_timeit', 'hello_world/bench.py'),
                                   'hello_world.bench.benchmark': ('bench.html#benchmark', 'hello_world/bench.py'),
                                   'hello_world.bench.gen': ('bench.html#gen', 'hello_world/bench.py'),
                                   'hello_world.bench.get_algs': ('bench.html#get_algs', 'hello_world/bench.py'),
                                   'hello_world.bench.main': ('bench.html#main', 'hello_world/bench.py'),
                                   'hello_world.bench.plot': ('bench.html#plot', 'hello_world/bench.py')},
            'hello_world.core': {'hello_world.core.foo': ('core.html#foo', 'hello_world/core.py')}}}
